### ISSUE TITLE
ByteCode.loadClass should use Application Classloader Hierarchy

### ISSUE THREAD

**Issue by almondtools** [almondtools/testrecorder#85]
Currently Classes in `ByteCode` are resolved with the current classloader. If the class to be resolved is loaded from a child class loader this will lead to exceptions. So there should always be a query to a class loader hierarchy beginning at the childmost classloader.

E.g. `ByteCode.classFrom(String):139`

**Comment by almondtools** [comment]
A related stacktrace:

`net.amygdalum.testrecorder.types.VirtualMethodSignature.fromDescriptor(VirtualMethodSignature.java:54)
	at net.amygdalum.testrecorder.ContextSnapshotFactory.signature(ContextSnapshotFactory.java:32)
	at net.amygdalum.testrecorder.MethodContext.signature(MethodContext.java:28)
	at net.amygdalum.testrecorder.SnapshotManager.matches(SnapshotManager.java:171)
	at net.amygdalum.testrecorder.SnapshotManager.throwVariables(SnapshotManager.java:422)

Caused by: net.amygdalum.testrecorder.asm.ByteCodeException: java.lang.ClassNotFoundException: com.enbw.eop.app.salesmachine.backend.overview.OverviewWorkflow
	at net.amygdalum.testrecorder.asm.ByteCode.loadClass(ByteCode.java:167)
	at net.amygdalum.testrecorder.asm.ByteCode.lambda$classFrom$7(ByteCode.java:156)
	at java.util.Optional.orElseGet(Optional.java:267)
	at net.amygdalum.testrecorder.asm.ByteCode.classFrom(ByteCode.java:156)
	at net.amygdalum.testrecorder.asm.ByteCode.classFrom(ByteCode.java:139)
	at net.amygdalum.testrecorder.types.VirtualMethodSignature.fromDescriptor(VirtualMethodSignature.java:49)
	... 63 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.enbw.eop.app.salesmachine.backend.overview.OverviewWorkflow
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.amygdalum.testrecorder.asm.ByteCode.loadClass(ByteCode.java:165)
	... 68 common frames omitted
`
