### ISSUE TITLE
Exception while using Testrecorder in Spring Boot Applications

### ISSUE THREAD

**Issue by kklaeger** [almondtools/testrecorder#96]
Hello everybody,

I'm using Testrecorder Version 0.10.0 with its standard configuration in a simple Spring Boot Application. If I start the application with the Testrecorder-Agent I'll get this Exception:
```
cannot load method com/testrecorder/TestrecorderSpringBootExampleApplication.setBeanFactory(Lorg/springframework/beans/factory/BeanFactory;)V
java.lang.NoSuchMethodException: setBeanFactory(Lorg/springframework/beans/factory/BeanFactory;)V
java.lang.NoSuchMethodException: setBeanFactory(Lorg/springframework/beans/factory/BeanFactory;)V
	at net.amygdalum.testrecorder.ClassNodeManager.fetch(ClassNodeManager.java:77)
	at net.amygdalum.testrecorder.SnapshotInstrumentor$Task.getNativeInputCalls(SnapshotInstrumentor.java:511)
	at net.amygdalum.testrecorder.SnapshotInstrumentor$Task.instrumentNativeInputCalls(SnapshotInstrumentor.java:357)
	at net.amygdalum.testrecorder.SnapshotInstrumentor$Task.access$100(SnapshotInstrumentor.java:232)
	at net.amygdalum.testrecorder.SnapshotInstrumentor.instrument(SnapshotInstrumentor.java:181)
	at net.amygdalum.testrecorder.SnapshotInstrumentor.instrument(SnapshotInstrumentor.java:158)
	at net.amygdalum.testrecorder.SnapshotInstrumentor.transform(SnapshotInstrumentor.java:132)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:523)
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:359)
	at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:582)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:106)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:104)
	at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:130)
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:315)
	at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:569)
	at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:416)
	at org.springframework.context.annotation.ConfigurationClassEnhancer.createClass(ConfigurationClassEnhancer.java:137)
	at org.springframework.context.annotation.ConfigurationClassEnhancer.enhance(ConfigurationClassEnhancer.java:109)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:402)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:253)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:286)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:130)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:691)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:528)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.testrecorder.TestrecorderSpringBootExampleApplication.main(TestrecorderSpringBootExampleApplication.java:10)
```
Is some further configuration necessary to use Testrecorder in a Spring Boot Application?

A solution for this problem would be nice. Thanks a lot.

**Comment by almondtools** [comment]
Spring Boot heavily uses byte code instrumentation - and sometimes this collides with Testrecorder. I recall some situations where similar exceptions occured right after starting the application. These errors did not affect the recording of methods however.

You may try out the example spring boot application [here](https://github.com/almondtools/testrecorder-application-examples/tree/master/testrecorder-spring). This application works for me and is correctly configured. I am not certain whether there are exception traces on startup. If so they may be ignored.

Yet I admit, that testrecorder is not very tolerant 
* with other frameworks changing byte code
* with frameworks making heavy use of java proxys

Recording proxied or instrumented classes is a bit tricky, so if you run into problems, feel free to share a short example with me, such that I can consult you how to solve this.

**Comment by almondtools** [comment]
Reanalyzing the problem I come to following explanation. Currently almost every Spring Boot Application will print this exception trace (also the example Spring Boot Application above):

```
recording snapshots of net/amygdalum/testrecorder/appexamples/spring/TodoApplication$$EnhancerBySpringCGLIB$$36a8d57d
cannot load method net/amygdalum/testrecorder/appexamples/spring/TodoApplication.setBeanFactory(Lorg/springframework/beans/factory/BeanFactory;)V
java.lang.NoSuchMethodException: setBeanFactory(Lorg/springframework/beans/factory/BeanFactory;)V
java.lang.NoSuchMethodException: setBeanFactory(Lorg/springframework/beans/factory/BeanFactory;)V
	at net.amygdalum.testrecorder.ClassNodeManager.fetch(ClassNodeManager.java:77)
...
```

This exception should usually be of low relevance, unless one wants to instrument a method generated by the CGLIBENHANCER of Spring. Every recording of true methods should work nonetheless.

Yet your report reminds me that a stack trace on the command line is often seen as indicator that something went totally wrong. 

My preferred approach to handle this problem would be to mute it, rather than to solve it.

**Comment by kklaeger** [comment]
First of all thank you very much for this detailed answer. Your solution solves the problem described above. Currently, I'm using the Testrecorder in a more complex application. If there are further problems I can share an example in a new issue. 

Thank you!
